Add historic advanced pv power
Solcast/solcast-api-python-sdk pull request #38
Opened 2024-07-04 01:18 UTC by lachlan-solcast

2024-07-04 04:05 UTC, lorenzo-solcast requested changes

2024-07-04 04:05 UTC, lorenzo-solcast commented on solcast/historic.py
> +        **kwargs: additional keyword arguments to be passed through as URL parameters to the Solcast API
kwargs is described twice

2024-07-04 05:15 UTC, lachlan-solcast commented on solcast/historic.py
> +        **kwargs: additional keyword arguments to be passed through as URL parameters to the Solcast API
Thanks, removed the duplicate

2024-07-04 05:33 UTC, lorenzo-solcast approved these changes

2024-07-05 00:38 UTC, lorenzo-solcast approved these changes

2024-07-05 00:38 UTC, merged